name: Hello Program

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build Node Project
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install

  deploy:
    runs-on: [hougitrn1-guru]
    
    steps:
    - name: Deploy to Dev server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIKEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.DEV_SERVER }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
    - name: Restart Service
      uses: nerd4ever/ssh-action@master
      with:
        command: |
          pm2 restart HelloWorld
        host: ${{ secrets.DEV_SERVER }}
        user: root
        key: ${{ secrets.SSH_PRIKEY}}
