name: Hello Program

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Trigger Manually' 

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Run npm start
        run: npm start
