name: Hello Program

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build Node Project
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - run: npm install

  deploy:
    runs-on: [self-hosted, Linux, X64]
    
    steps:
    - name: Deploy to Dev server
      uses: easingthemes/ssh-deploy@main
      with:
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/app/"
          EXCLUDE: "/dist/, /node_modules/"
